age = input('How old are you?')
number = int(age)
next = (number + 1)
print()
print(f'On your next birthday you will be {next} years old!')

print()
cartons = input('How many egg cartons do you have in your fridge?')
numberTwo = int(cartons)
eggs = (numberTwo * 12)
print()
print(f'You have {eggs} eggs in your fridge.')

print()
cookies = input('How many cookies do you have?')
numC = int(cookies)
people = input('How many people are coming to your party?')
numP = int(people)
share = (numC / numP)
print()
print(f'Each person can have {share} cookies!')
