print("Welcome to the Band Name Generator!")
print()
city = input("What is the name of the city you grew up in?\n")
pet = input("What is the name of your first pet? \n")
print()
print(f"Your band name could be {city.capitalize()} {pet.capitalize()}.")
